export const LOAD_REQUEST = "LOAD_REQUEST";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGN_OUT = "SIGN_OUT";
export const CHECK_TOKEN_VALIDITY = "CHECK_TOKEN_VALIDITY";

export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_ERROR = "CREATE_SESSION_ERROR";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_ERROR = "GET_SESSIONS_ERROR";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_SESSION_ERROR = "GET_SESSION_ERROR";
export const EDIT_SESSION = "EDIT_SESSION";
export const RESET_SESSION = "RESET_SESSION";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_ERROR = "UPDATE_SESSION_ERROR";

export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_ERROR = "ADD_NOTE_ERROR";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR";
export const START_NEW_NOTE = "START_NEW_NOTE";
export const CANCEL_START_NEW_NOTE = "CANCEL_EDIT_NEW_NOTE";
export const EDIT_NEW_NOTE = "EDIT_NEW_NOTE";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_ERROR = "UPDATE_NOTE_ERROR";
